[2024-05-03T21:51:10.483+0000] {processor.py:153} INFO - Started process (PID=190) to work on /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:51:10.485+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/health_journal_reminder_d.py for tasks to queue
[2024-05-03T21:51:10.487+0000] {logging_mixin.py:137} INFO - [2024-05-03T21:51:10.487+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:51:10.502+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:51:10.623+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/health_journal_reminder_d.py took 0.151 seconds
[2024-05-03T21:51:41.172+0000] {processor.py:153} INFO - Started process (PID=210) to work on /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:51:41.176+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/health_journal_reminder_d.py for tasks to queue
[2024-05-03T21:51:41.177+0000] {logging_mixin.py:137} INFO - [2024-05-03T21:51:41.177+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:51:41.185+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:51:41.277+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/health_journal_reminder_d.py took 0.118 seconds
[2024-05-03T21:51:51.351+0000] {processor.py:153} INFO - Started process (PID=215) to work on /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:51:51.354+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/health_journal_reminder_d.py for tasks to queue
[2024-05-03T21:51:51.355+0000] {logging_mixin.py:137} INFO - [2024-05-03T21:51:51.355+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:51:51.384+0000] {logging_mixin.py:137} INFO - [2024-05-03T21:51:51.380+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/health_journal_reminder_d.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/health_journal_reminder_d.py", line 4, in <module>
    from app.services.conversation_service import ConversationService
ModuleNotFoundError: No module named 'app'
[2024-05-03T21:51:51.385+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:51:51.494+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/health_journal_reminder_d.py took 0.148 seconds
[2024-05-03T21:52:21.918+0000] {processor.py:153} INFO - Started process (PID=220) to work on /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:52:21.923+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/health_journal_reminder_d.py for tasks to queue
[2024-05-03T21:52:21.926+0000] {logging_mixin.py:137} INFO - [2024-05-03T21:52:21.925+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:52:21.954+0000] {logging_mixin.py:137} INFO - [2024-05-03T21:52:21.950+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/health_journal_reminder_d.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/health_journal_reminder_d.py", line 4, in <module>
    from app.services.conversation_service import ConversationService
ModuleNotFoundError: No module named 'app'
[2024-05-03T21:52:21.956+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:52:22.070+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/health_journal_reminder_d.py took 0.159 seconds
[2024-05-03T21:52:52.449+0000] {processor.py:153} INFO - Started process (PID=225) to work on /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:52:52.452+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/health_journal_reminder_d.py for tasks to queue
[2024-05-03T21:52:52.454+0000] {logging_mixin.py:137} INFO - [2024-05-03T21:52:52.454+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:52:52.485+0000] {logging_mixin.py:137} INFO - [2024-05-03T21:52:52.475+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/health_journal_reminder_d.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/health_journal_reminder_d.py", line 4, in <module>
    from app.services.conversation_service import ConversationService
ModuleNotFoundError: No module named 'app'
[2024-05-03T21:52:52.487+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:52:52.599+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/health_journal_reminder_d.py took 0.154 seconds
[2024-05-03T21:53:22.926+0000] {processor.py:153} INFO - Started process (PID=230) to work on /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:53:22.928+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/health_journal_reminder_d.py for tasks to queue
[2024-05-03T21:53:22.930+0000] {logging_mixin.py:137} INFO - [2024-05-03T21:53:22.930+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:53:22.957+0000] {logging_mixin.py:137} INFO - [2024-05-03T21:53:22.954+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/health_journal_reminder_d.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/health_journal_reminder_d.py", line 4, in <module>
    from app.services.conversation_service import ConversationService
ModuleNotFoundError: No module named 'app'
[2024-05-03T21:53:22.958+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:53:23.061+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/health_journal_reminder_d.py took 0.140 seconds
[2024-05-03T21:53:53.734+0000] {processor.py:153} INFO - Started process (PID=235) to work on /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:53:53.743+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/health_journal_reminder_d.py for tasks to queue
[2024-05-03T21:53:53.745+0000] {logging_mixin.py:137} INFO - [2024-05-03T21:53:53.744+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:53:53.770+0000] {logging_mixin.py:137} INFO - [2024-05-03T21:53:53.767+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/health_journal_reminder_d.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/health_journal_reminder_d.py", line 4, in <module>
    from app.services.conversation_service import ConversationService
ModuleNotFoundError: No module named 'app'
[2024-05-03T21:53:53.772+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:53:53.889+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/health_journal_reminder_d.py took 0.162 seconds
[2024-05-03T21:54:16.117+0000] {processor.py:153} INFO - Started process (PID=240) to work on /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:54:16.121+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/health_journal_reminder_d.py for tasks to queue
[2024-05-03T21:54:16.122+0000] {logging_mixin.py:137} INFO - [2024-05-03T21:54:16.122+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:54:16.184+0000] {logging_mixin.py:137} INFO - [2024-05-03T21:54:16.171+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/health_journal_reminder_d.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/health_journal_reminder_d.py", line 4, in <module>
    from .services.conversation_service import ConversationService
ImportError: attempted relative import with no known parent package
[2024-05-03T21:54:16.185+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:54:16.317+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/health_journal_reminder_d.py took 0.210 seconds
[2024-05-03T21:54:46.739+0000] {processor.py:153} INFO - Started process (PID=245) to work on /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:54:46.748+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/health_journal_reminder_d.py for tasks to queue
[2024-05-03T21:54:46.751+0000] {logging_mixin.py:137} INFO - [2024-05-03T21:54:46.751+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:54:46.843+0000] {logging_mixin.py:137} INFO - [2024-05-03T21:54:46.792+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/health_journal_reminder_d.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/health_journal_reminder_d.py", line 4, in <module>
    from ..services.conversation_service import ConversationService
ImportError: attempted relative import with no known parent package
[2024-05-03T21:54:46.846+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:54:46.984+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/health_journal_reminder_d.py took 0.252 seconds
[2024-05-03T21:54:54.944+0000] {processor.py:153} INFO - Started process (PID=250) to work on /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:54:54.947+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/health_journal_reminder_d.py for tasks to queue
[2024-05-03T21:54:54.948+0000] {logging_mixin.py:137} INFO - [2024-05-03T21:54:54.948+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:54:54.978+0000] {logging_mixin.py:137} INFO - [2024-05-03T21:54:54.971+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/health_journal_reminder_d.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/health_journal_reminder_d.py", line 6, in <module>
    from ..services.conversation_service import ConversationService
ImportError: attempted relative import with no known parent package
[2024-05-03T21:54:54.980+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:54:55.095+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/health_journal_reminder_d.py took 0.160 seconds
[2024-05-03T21:54:57.197+0000] {processor.py:153} INFO - Started process (PID=255) to work on /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:54:57.201+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/health_journal_reminder_d.py for tasks to queue
[2024-05-03T21:54:57.202+0000] {logging_mixin.py:137} INFO - [2024-05-03T21:54:57.202+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:54:57.238+0000] {logging_mixin.py:137} INFO - [2024-05-03T21:54:57.234+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/health_journal_reminder_d.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/health_journal_reminder_d.py", line 7, in <module>
    from ..services.conversation_service import ConversationService
ImportError: attempted relative import with no known parent package
[2024-05-03T21:54:57.240+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:54:57.350+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/health_journal_reminder_d.py took 0.158 seconds
[2024-05-03T21:54:59.331+0000] {processor.py:153} INFO - Started process (PID=260) to work on /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:54:59.334+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/health_journal_reminder_d.py for tasks to queue
[2024-05-03T21:54:59.336+0000] {logging_mixin.py:137} INFO - [2024-05-03T21:54:59.336+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:54:59.389+0000] {logging_mixin.py:137} INFO - [2024-05-03T21:54:59.384+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/health_journal_reminder_d.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/health_journal_reminder_d.py", line 7, in <module>
    from services.conversation_service import ConversationService
ModuleNotFoundError: No module named 'services'
[2024-05-03T21:54:59.391+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:54:59.570+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/health_journal_reminder_d.py took 0.255 seconds
[2024-05-03T21:55:01.500+0000] {processor.py:153} INFO - Started process (PID=265) to work on /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:55:01.503+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/health_journal_reminder_d.py for tasks to queue
[2024-05-03T21:55:01.504+0000] {logging_mixin.py:137} INFO - [2024-05-03T21:55:01.504+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:55:01.542+0000] {logging_mixin.py:137} INFO - [2024-05-03T21:55:01.531+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/health_journal_reminder_d.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/health_journal_reminder_d.py", line 7, in <module>
    from backservices.conversation_service import ConversationService
ModuleNotFoundError: No module named 'backservices'
[2024-05-03T21:55:01.544+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:55:01.650+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/health_journal_reminder_d.py took 0.156 seconds
[2024-05-03T21:55:03.641+0000] {processor.py:153} INFO - Started process (PID=270) to work on /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:55:03.643+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/health_journal_reminder_d.py for tasks to queue
[2024-05-03T21:55:03.644+0000] {logging_mixin.py:137} INFO - [2024-05-03T21:55:03.644+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:55:03.667+0000] {logging_mixin.py:137} INFO - [2024-05-03T21:55:03.663+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/health_journal_reminder_d.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/health_journal_reminder_d.py", line 7, in <module>
    from backendservices.conversation_service import ConversationService
ModuleNotFoundError: No module named 'backendservices'
[2024-05-03T21:55:03.668+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:55:03.754+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/health_journal_reminder_d.py took 0.116 seconds
[2024-05-03T21:55:06.773+0000] {processor.py:153} INFO - Started process (PID=275) to work on /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:55:06.776+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/health_journal_reminder_d.py for tasks to queue
[2024-05-03T21:55:06.778+0000] {logging_mixin.py:137} INFO - [2024-05-03T21:55:06.777+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:55:06.827+0000] {logging_mixin.py:137} INFO - [2024-05-03T21:55:06.824+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/health_journal_reminder_d.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/health_journal_reminder_d.py", line 7, in <module>
    from backend.app.services.conversation_service import ConversationService
ModuleNotFoundError: No module named 'backend'
[2024-05-03T21:55:06.828+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:55:06.929+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/health_journal_reminder_d.py took 0.162 seconds
[2024-05-03T21:55:37.483+0000] {processor.py:153} INFO - Started process (PID=280) to work on /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:55:37.486+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/health_journal_reminder_d.py for tasks to queue
[2024-05-03T21:55:37.488+0000] {logging_mixin.py:137} INFO - [2024-05-03T21:55:37.488+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:55:37.513+0000] {logging_mixin.py:137} INFO - [2024-05-03T21:55:37.511+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/health_journal_reminder_d.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/health_journal_reminder_d.py", line 7, in <module>
    from backend.app.services.conversation_service import ConversationService
ModuleNotFoundError: No module named 'backend'
[2024-05-03T21:55:37.515+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:55:37.616+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/health_journal_reminder_d.py took 0.140 seconds
[2024-05-03T21:56:08.007+0000] {processor.py:153} INFO - Started process (PID=285) to work on /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:56:08.010+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/health_journal_reminder_d.py for tasks to queue
[2024-05-03T21:56:08.012+0000] {logging_mixin.py:137} INFO - [2024-05-03T21:56:08.012+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:56:08.041+0000] {logging_mixin.py:137} INFO - [2024-05-03T21:56:08.039+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/health_journal_reminder_d.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/health_journal_reminder_d.py", line 7, in <module>
    from backend.app.services.conversation_service import ConversationService
ModuleNotFoundError: No module named 'backend'
[2024-05-03T21:56:08.042+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:56:08.172+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/health_journal_reminder_d.py took 0.169 seconds
[2024-05-03T21:56:38.595+0000] {processor.py:153} INFO - Started process (PID=290) to work on /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:56:38.599+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/health_journal_reminder_d.py for tasks to queue
[2024-05-03T21:56:38.601+0000] {logging_mixin.py:137} INFO - [2024-05-03T21:56:38.601+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:56:38.621+0000] {logging_mixin.py:137} INFO - [2024-05-03T21:56:38.618+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/health_journal_reminder_d.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/health_journal_reminder_d.py", line 7, in <module>
    from backend.app.services.conversation_service import ConversationService
ModuleNotFoundError: No module named 'backend'
[2024-05-03T21:56:38.622+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:56:38.755+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/health_journal_reminder_d.py took 0.166 seconds
[2024-05-03T21:57:09.130+0000] {processor.py:153} INFO - Started process (PID=295) to work on /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:57:09.133+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/health_journal_reminder_d.py for tasks to queue
[2024-05-03T21:57:09.135+0000] {logging_mixin.py:137} INFO - [2024-05-03T21:57:09.134+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:57:09.154+0000] {logging_mixin.py:137} INFO - [2024-05-03T21:57:09.151+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/health_journal_reminder_d.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/health_journal_reminder_d.py", line 7, in <module>
    from backend.app.services.conversation_service import ConversationService
ModuleNotFoundError: No module named 'backend'
[2024-05-03T21:57:09.155+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:57:09.280+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/health_journal_reminder_d.py took 0.156 seconds
[2024-05-03T21:57:39.887+0000] {processor.py:153} INFO - Started process (PID=300) to work on /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:57:39.890+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/health_journal_reminder_d.py for tasks to queue
[2024-05-03T21:57:39.891+0000] {logging_mixin.py:137} INFO - [2024-05-03T21:57:39.891+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:57:39.914+0000] {logging_mixin.py:137} INFO - [2024-05-03T21:57:39.907+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/health_journal_reminder_d.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/health_journal_reminder_d.py", line 7, in <module>
    from backend.app.services.conversation_service import ConversationService
ModuleNotFoundError: No module named 'backend'
[2024-05-03T21:57:39.917+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:57:40.037+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/health_journal_reminder_d.py took 0.153 seconds
[2024-05-03T21:58:10.475+0000] {processor.py:153} INFO - Started process (PID=305) to work on /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:58:10.478+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/health_journal_reminder_d.py for tasks to queue
[2024-05-03T21:58:10.479+0000] {logging_mixin.py:137} INFO - [2024-05-03T21:58:10.479+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:58:10.493+0000] {logging_mixin.py:137} INFO - [2024-05-03T21:58:10.491+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/health_journal_reminder_d.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/health_journal_reminder_d.py", line 7, in <module>
    from backend.app.services.conversation_service import ConversationService
ModuleNotFoundError: No module named 'backend'
[2024-05-03T21:58:10.493+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/health_journal_reminder_d.py
[2024-05-03T21:58:10.610+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/health_journal_reminder_d.py took 0.139 seconds
